[package]
name = "motion_detection"
version = "1.0.0"
edition = "2023"
description = "Detects motion using OpenCV"
license = "MIT"
authors = ["RISHI BARUA"]

[dependencies]
python-opencv = { version = ">=4.5.1", git = "https://github.com/RISHI9922/MOTION.PYTHON.PKG.git" }

[build-system]
requires = ["python>=3.6"]
build-backend = "setuptools.build_meta"
